### ISSUE TITLE
Some hints at extending the annotations

### ISSUE THREAD

**Issue by davidwynter** [ZeroarcSoftware/carbondream#6]
Can you give some hints on how we would extend the annotator to have 2 new features?

1. We need to convert the React document into a Word document at some point, thus we need to add a number in the top left of each annotation to identify it in the exported document. A small circle with a number in it would work.
2. The UI Design calls for a palette that has 5 different rectangles to be used for annotation, with different cross hatch patterns scaled to fill the rectangle.

**Comment by jslatts** [comment]
Hey David,

1. Are you referring to the markers themselves or the pop ups that are activated on mouse over? If you want to add the number to the pop up, take a look at src/Context.jsx. It would be pretty straightforward to add a prop for the annotation "number" and display it. 

If you want to add this number to the indicator (pin, circle, square, etc) then it might make the most sense to create a custom indicator (depending on your specific needs).

2. Again, are we referring to the pop ups or the indicator rectangle? If the latter, then I think the direction of adding additional indicator types (variations of the square) would make the most sense. If the patterns can be made with CSS, then you could re-use the existing square and just add different CSS classes.

Let me know if any of that makes sense. I would be happy to accept pull requests if you can keep the changes optional for existing users.

**Comment by jslatts** [comment]
Closing issues older than 1 year.
